name = "travelplannerai"
main = "src/index.ts"
compatibility_date = "2024-01-17"

# We will use the variables you set in the dashboard, 
# but we can also define them here if we wanted to (except secrets).
# vars = { FIREBASE_PROJECT_ID = "..." }

[dependencies]
jose = "^5.2.0"
